script: rake ci
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode 

matrix:
  allow_failures:
    - rvm: rbx-19mode # segvs o_O

notifications:
  irc: "irc.freenode.org#celluloid"
