script: rake ci
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
#  - jruby-head # FIXME: timers firing in the wrong order?
  - rbx-19mode

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

notifications:
  irc: "irc.freenode.org#celluloid"
