script: rake ci
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode 

matrix:
  allow_failures:
    - rvm: 1.9.3 # segvs o_O https://github.com/travis-ci/travis-ci/issues/827
    - rvm: rbx-19mode # segvs o_O

notifications:
  irc: "irc.freenode.org#celluloid"
